// @generated by scripts/generate_acceptance_tests.py — DO NOT EDIT.
// Source of truth: pipeUITests/Features/*.feature
// Regenerate with: python3 scripts/generate_acceptance_tests.py
import XCTest

extension AcceptanceTests {


    // MARK: - Audio and Video Playback Mode

    func test_Toggling_video_mode_from_the_full_player() {
        runScenario(feature: "audio_video_mode.feature", scenario: "Toggling video mode from the full player")
    }


    // MARK: - Channel Browsing

    func test_Opening_a_channel_shows_its_videos() {
        runScenario(feature: "channel_browsing.feature", scenario: "Opening a channel shows its videos")
    }


    // MARK: - Channel Metadata

    func test_Channel_results_show_subscriber_count_and_verified_badge() {
        runScenario(feature: "channel_metadata.feature", scenario: "Channel results show subscriber count and verified badge")
    }


    // MARK: - Chapters

    func test_Opening_a_video_with_chapters_shows_a_tappable_chapter_list() {
        runScenario(feature: "chapters.feature", scenario: "Opening a video with chapters shows a tappable chapter list")
    }

    func test_The_full_player_shows_the_current_chapter() {
        runScenario(feature: "chapters.feature", scenario: "The full player shows the current chapter")
    }


    // MARK: - Comments

    func test_Opening_comments_shows_them() {
        runScenario(feature: "comments.feature", scenario: "Opening comments shows them")
    }


    // MARK: - Diagnostics log

    func test_Settings_exposes_a_diagnostics_section() {
        runScenario(feature: "diagnostics.feature", scenario: "Settings exposes a diagnostics section")
    }

    func test_Diagnostics_upload_is_off_by_default_and_can_be_turned_on() {
        runScenario(feature: "diagnostics.feature", scenario: "Diagnostics upload is off by default and can be turned on")
    }


    // MARK: - Offline Downloads

    func test_Empty_downloads_state() {
        runScenario(feature: "downloads.feature", scenario: "Empty downloads state")
    }

    func test_Downloading_a_video_adds_it_to_Downloads() {
        runScenario(feature: "downloads.feature", scenario: "Downloading a video adds it to Downloads")
    }

    func test_Downloading_from_a_search_result_s_context_menu() {
        runScenario(feature: "downloads.feature", scenario: "Downloading from a search result's context menu")
    }

    func test_Downloads_screen_shows_storage_used() {
        runScenario(feature: "downloads.feature", scenario: "Downloads screen shows storage used")
    }


    // MARK: - Error Recovery

    func test_Detail_view_offers_retry_on_failure() {
        runScenario(feature: "error_recovery.feature", scenario: "Detail view offers retry on failure")
    }

    func test_Queueing_a_failed_stream_explains_why_it_couldn_t_be_added() {
        runScenario(feature: "error_recovery.feature", scenario: "Queueing a failed stream explains why it couldn't be added")
    }


    // MARK: - Feed Sorting and Filtering

    func test_Feed_offers_sort_and_hide_watched_options() {
        runScenario(feature: "feed_sorting.feature", scenario: "Feed offers sort and hide-watched options")
    }


    // MARK: - Following Channels

    func test_Empty_following_state() {
        runScenario(feature: "following.feature", scenario: "Empty following state")
    }

    func test_Following_a_channel_from_search() {
        runScenario(feature: "following.feature", scenario: "Following a channel from search")
    }


    // MARK: - Full Player Tabs

    func test_Up_Next_is_reachable_from_the_full_player() {
        runScenario(feature: "full_player.feature", scenario: "Up Next is reachable from the full player")
    }

    func test_Comments_are_reachable_from_the_full_player() {
        runScenario(feature: "full_player.feature", scenario: "Comments are reachable from the full player")
    }

    func test_Info_tab_shows_the_description_as_readable_text() {
        runScenario(feature: "full_player.feature", scenario: "Info tab shows the description as readable text")
    }

    func test_Chapters_tab_lists_chapters_and_seeks_on_tap() {
        runScenario(feature: "full_player.feature", scenario: "Chapters tab lists chapters and seeks on tap")
    }


    // MARK: - Offline Mode

    func test_Enabling_offline_mode_opens_Downloads() {
        runScenario(feature: "offline_mode.feature", scenario: "Enabling offline mode opens Downloads")
    }

    func test_Search_shows_an_offline_state_when_offline_mode_is_on() {
        runScenario(feature: "offline_mode.feature", scenario: "Search shows an offline state when offline mode is on")
    }

    func test_Following_still_works_offline() {
        runScenario(feature: "offline_mode.feature", scenario: "Following still works offline")
    }


    // MARK: - Picture in Picture

    func test_Video_mode_presents_a_PiP_capable_player() {
        runScenario(feature: "picture_in_picture.feature", scenario: "Video mode presents a PiP-capable player")
    }

    func test_Pausing_the_video_mode_player_pauses_playback() {
        runScenario(feature: "picture_in_picture.feature", scenario: "Pausing the video-mode player pauses playback")
    }


    // MARK: - Play Next

    func test_Play_Next_is_offered_in_a_result_s_context_menu() {
        runScenario(feature: "play_next.feature", scenario: "Play Next is offered in a result's context menu")
    }


    // MARK: - Video Playback

    func test_Playing_a_result_starts_the_mini_player() {
        runScenario(feature: "playback.feature", scenario: "Playing a result starts the mini player")
    }

    func test_Expanding_the_mini_player_shows_full_controls() {
        runScenario(feature: "playback.feature", scenario: "Expanding the mini player shows full controls")
    }


    // MARK: - Playlists

    func test_A_channel_s_Playlists_tab_lists_its_playlists() {
        runScenario(feature: "playlists.feature", scenario: "A channel's Playlists tab lists its playlists")
    }

    func test_Opening_a_playlist_shows_its_videos() {
        runScenario(feature: "playlists.feature", scenario: "Opening a playlist shows its videos")
    }

    func test_Play_All_queues_the_playlist() {
        runScenario(feature: "playlists.feature", scenario: "Play All queues the playlist")
    }

    func test_Saving_a_playlist_keeps_it_in_Saved_Playlists() {
        runScenario(feature: "playlists.feature", scenario: "Saving a playlist keeps it in Saved Playlists")
    }

    func test_Playlist_results_appear_in_search() {
        runScenario(feature: "playlists.feature", scenario: "Playlist results appear in search")
    }


    // MARK: - Playback Queue

    func test_Queueing_a_result_adds_it_to_the_queue() {
        runScenario(feature: "queue.feature", scenario: "Queueing a result adds it to the queue")
    }

    func test_A_video_with_a_malformed_related_entry_still_plays() {
        runScenario(feature: "queue.feature", scenario: "A video with a malformed related entry still plays")
    }


    // MARK: - Recently Played

    func test_Empty_recents_state() {
        runScenario(feature: "recents.feature", scenario: "Empty recents state")
    }

    func test_Playing_a_video_records_it_in_Recents() {
        runScenario(feature: "recents.feature", scenario: "Playing a video records it in Recents")
    }


    // MARK: - Save for Later

    func test_Empty_saved_state() {
        runScenario(feature: "save_for_later.feature", scenario: "Empty saved state")
    }


    // MARK: - Search Videos

    func test_Empty_state_shows_suggestions() {
        runScenario(feature: "search.feature", scenario: "Empty state shows suggestions")
    }

    func test_Searching_returns_results() {
        runScenario(feature: "search.feature", scenario: "Searching returns results")
    }

    func test_Tapping_a_suggestion_runs_a_search() {
        runScenario(feature: "search.feature", scenario: "Tapping a suggestion runs a search")
    }


    // MARK: - Search As You Type

    func test_Typing_a_query_shows_results_without_submitting() {
        runScenario(feature: "search_as_you_type.feature", scenario: "Typing a query shows results without submitting")
    }


    // MARK: - Search History

    func test_A_performed_search_is_remembered() {
        runScenario(feature: "search_history.feature", scenario: "A performed search is remembered")
    }


    // MARK: - Settings

    func test_Settings_screen_shows_its_sections() {
        runScenario(feature: "settings.feature", scenario: "Settings screen shows its sections")
    }

    func test_Setting_a_sleep_timer_shows_the_countdown() {
        runScenario(feature: "settings.feature", scenario: "Setting a sleep timer shows the countdown")
    }

    func test_Clearing_search_history_empties_it() {
        runScenario(feature: "settings.feature", scenario: "Clearing search history empties it")
    }


    // MARK: - Sleep Timer End of Episode

    func test_Setting_an_end_of_episode_sleep_timer_shows_its_state() {
        runScenario(feature: "sleep_timer.feature", scenario: "Setting an end-of-episode sleep timer shows its state")
    }


    // MARK: - SponsorBlock

    func test_SponsorBlock_is_on_by_default_and_can_be_turned_off() {
        runScenario(feature: "sponsorblock.feature", scenario: "SponsorBlock is on by default and can be turned off")
    }


    // MARK: - Tab Navigation

    func test_All_tabs_are_reachable() {
        runScenario(feature: "tab_navigation.feature", scenario: "All tabs are reachable")
    }


    // MARK: - Transcript

    func test_Transcript_tab_is_reachable_from_the_full_player() {
        runScenario(feature: "transcript.feature", scenario: "Transcript tab is reachable from the full player")
    }


    // MARK: - Trending

    func test_Opening_Trending_shows_videos() {
        runScenario(feature: "trending.feature", scenario: "Opening Trending shows videos")
    }


    // MARK: - Up Next

    func test_A_video_s_detail_shows_related_videos() {
        runScenario(feature: "up_next.feature", scenario: "A video's detail shows related videos")
    }


    // MARK: - Watch History Management

    func test_Clearing_watch_history() {
        runScenario(feature: "watch_history_management.feature", scenario: "Clearing watch history")
    }

}
