// @generated by scripts/generate_acceptance_tests.py — DO NOT EDIT.
// Source of truth: pipeUITests/Features/*.feature
// Regenerate with: python3 scripts/generate_acceptance_tests.py
import XCTest

extension AcceptanceTests {


    // MARK: - Audio and Video Playback Mode

    func test_Toggling_video_mode_from_the_full_player() {
        runScenario(feature: "audio_video_mode.feature", scenario: "Toggling video mode from the full player")
    }


    // MARK: - Channel Browsing

    func test_Opening_a_channel_shows_its_videos() {
        runScenario(feature: "channel_browsing.feature", scenario: "Opening a channel shows its videos")
    }


    // MARK: - Error Recovery

    func test_Detail_view_offers_retry_on_failure() {
        runScenario(feature: "error_recovery.feature", scenario: "Detail view offers retry on failure")
    }


    // MARK: - Feed Sorting and Filtering

    func test_Feed_offers_sort_and_hide_watched_options() {
        runScenario(feature: "feed_sorting.feature", scenario: "Feed offers sort and hide-watched options")
    }


    // MARK: - Following Channels

    func test_Empty_following_state() {
        runScenario(feature: "following.feature", scenario: "Empty following state")
    }

    func test_Following_a_channel_from_search() {
        runScenario(feature: "following.feature", scenario: "Following a channel from search")
    }


    // MARK: - Picture in Picture

    func test_Video_mode_presents_a_PiP_capable_player() {
        runScenario(feature: "picture_in_picture.feature", scenario: "Video mode presents a PiP-capable player")
    }


    // MARK: - Video Playback

    func test_Playing_a_result_starts_the_mini_player() {
        runScenario(feature: "playback.feature", scenario: "Playing a result starts the mini player")
    }

    func test_Expanding_the_mini_player_shows_full_controls() {
        runScenario(feature: "playback.feature", scenario: "Expanding the mini player shows full controls")
    }


    // MARK: - Playback Queue

    func test_Queueing_a_result_adds_it_to_the_queue() {
        runScenario(feature: "queue.feature", scenario: "Queueing a result adds it to the queue")
    }


    // MARK: - Recently Played

    func test_Empty_recents_state() {
        runScenario(feature: "recents.feature", scenario: "Empty recents state")
    }

    func test_Playing_a_video_records_it_in_Recents() {
        runScenario(feature: "recents.feature", scenario: "Playing a video records it in Recents")
    }


    // MARK: - Save for Later

    func test_Empty_saved_state() {
        runScenario(feature: "save_for_later.feature", scenario: "Empty saved state")
    }


    // MARK: - Search Videos

    func test_Empty_state_shows_suggestions() {
        runScenario(feature: "search.feature", scenario: "Empty state shows suggestions")
    }

    func test_Searching_returns_results() {
        runScenario(feature: "search.feature", scenario: "Searching returns results")
    }

    func test_Tapping_a_suggestion_runs_a_search() {
        runScenario(feature: "search.feature", scenario: "Tapping a suggestion runs a search")
    }


    // MARK: - Search History

    func test_A_performed_search_is_remembered() {
        runScenario(feature: "search_history.feature", scenario: "A performed search is remembered")
    }


    // MARK: - Settings

    func test_Settings_screen_shows_its_sections() {
        runScenario(feature: "settings.feature", scenario: "Settings screen shows its sections")
    }

    func test_Setting_a_sleep_timer_shows_the_countdown() {
        runScenario(feature: "settings.feature", scenario: "Setting a sleep timer shows the countdown")
    }

    func test_Clearing_search_history_empties_it() {
        runScenario(feature: "settings.feature", scenario: "Clearing search history empties it")
    }


    // MARK: - Tab Navigation

    func test_All_tabs_are_reachable() {
        runScenario(feature: "tab_navigation.feature", scenario: "All tabs are reachable")
    }


    // MARK: - Watch History Management

    func test_Clearing_watch_history() {
        runScenario(feature: "watch_history_management.feature", scenario: "Clearing watch history")
    }

}
