import Testing
import Foundation
@testable import pipe

/// Controllable summarizer double: emits the given snapshots, or throws.
@MainActor
private final class MockSummarizer: Summarizing {
    var isAvailable: Bool
    var snapshots: [String]
    var error: Error?

    init(available: Bool = true, snapshots: [String] = [], error: Error? = nil) {
        self.isAvailable = available
        self.snapshots = snapshots
        self.error = error
    }

    func stream(_ text: String) -> AsyncThrowingStream<String, Error> {
        AsyncThrowingStream { continuation in
            for s in snapshots { continuation.yield(s) }
            if let error { continuation.finish(throwing: error) } else { continuation.finish() }
        }
    }
}

private let ttmlFixture = """
<tt><body><div>
<p begin="00:00:01.000">hello</p>
<p begin="00:00:02.000">world</p>
</div></body></tt>
"""

@MainActor
struct TranscriptStoreTests {

    private func store(_ mock: MockSummarizer,
                       fetch: @escaping (URL) async throws -> String) -> TranscriptStore {
        TranscriptStore(summarizer: mock, preferredLanguage: "en", fetch: fetch)
    }

    private let subs = [Subtitle(url: "https://x/en.ttml", name: "English", code: "en", autoGenerated: false)]

    @Test func loadsCuesFromTrack() async {
        let s = store(MockSummarizer()) { _ in ttmlFixture }
        await s.load(subtitles: subs, videoId: "v1")
        #expect(s.state.value?.count == 2)
        #expect(s.state.value?.first?.text == "hello")
    }

    @Test func failsWhenNoSubtitles() async {
        let s = store(MockSummarizer()) { _ in ttmlFixture }
        await s.load(subtitles: nil, videoId: "v1")
        #expect(s.state.didFail)
    }

    @Test func failsWhenTrackEmpty() async {
        let s = store(MockSummarizer()) { _ in "no cues here" }
        await s.load(subtitles: subs, videoId: "v1")
        #expect(s.state.didFail)
    }

    @Test func nilVideoResetsToLoading() async {
        let s = store(MockSummarizer()) { _ in ttmlFixture }
        await s.load(subtitles: subs, videoId: "v1")
        await s.load(subtitles: subs, videoId: nil)
        #expect(s.state.isLoading)
    }

    @Test func canSummarizeFollowsAvailability() {
        #expect(store(MockSummarizer(available: true)) { _ in "" }.canSummarize)
        #expect(!(store(MockSummarizer(available: false)) { _ in "" }.canSummarize))
    }

    @Test func summarizeAppendsStreamedSnapshots() async {
        let mock = MockSummarizer(snapshots: ["Sum", "Summary"])
        let s = store(mock) { _ in ttmlFixture }
        await s.load(subtitles: subs, videoId: "v1")
        s.summarize()
        // Poll until the streamed task settles (isSummarizing flips back).
        var elapsed: UInt64 = 0
        while s.isSummarizing && elapsed < 2_000_000_000 {
            try? await Task.sleep(nanoseconds: 20_000_000)
            elapsed += 20_000_000
        }
        #expect(s.summary == "Summary")
    }

    @Test func summarizeSurfacesErrorText() async {
        struct Boom: Error {}
        let mock = MockSummarizer(snapshots: [], error: Boom())
        let s = store(mock) { _ in ttmlFixture }
        await s.load(subtitles: subs, videoId: "v1")
        s.summarize()
        var elapsed: UInt64 = 0
        while s.isSummarizing && elapsed < 2_000_000_000 {
            try? await Task.sleep(nanoseconds: 20_000_000)
            elapsed += 20_000_000
        }
        #expect(s.summary == "Couldn't summarize — try again.")
    }

    @Test func summarizeNoOpWithoutLoadedTranscript() {
        let s = store(MockSummarizer()) { _ in "" }
        s.summarize()   // state is still .loading
        #expect(!s.isSummarizing)
        #expect(s.summary.isEmpty)
    }
}
