import Testing
import Foundation
@testable import pipe

struct TranscriptLogicTests {

    // MARK: - seconds(fromClock:)

    @Test func parsesFullClock() {
        #expect(TranscriptLogic.seconds(fromClock: "00:00:01.360") == 1.36)
        #expect(TranscriptLogic.seconds(fromClock: "01:02:03") == 3723)
        #expect(TranscriptLogic.seconds(fromClock: "02:05") == 125)
        #expect(TranscriptLogic.seconds(fromClock: "9.5") == 9.5)
    }

    @Test func rejectsBadClock() {
        #expect(TranscriptLogic.seconds(fromClock: "abc") == nil)
        #expect(TranscriptLogic.seconds(fromClock: "") == nil)
        #expect(TranscriptLogic.seconds(fromClock: "1:2:3:4") == nil)
    }

    // MARK: - parseTTML

    private let ttml = """
    <?xml version="1.0"?>
    <tt><body region="r1"><div>
    <p begin="00:00:01.360" end="00:00:03.040">[♪♪♪]</p>
    <p begin="00:00:18.640" end="00:00:21.880">We&#39;re no strangers<br />to love</p>
    <p begin="00:00:22.640" end="00:00:26.960">   </p>
    </div></body></tt>
    """

    @Test func parsesCuesInOrder() {
        let cues = TranscriptLogic.parseTTML(ttml)
        #expect(cues.count == 2)   // the whitespace-only cue is dropped
        #expect(cues[0].start == 1.36)
        #expect(cues[0].text == "[♪♪♪]")
        #expect(cues[1].start == 18.64)
    }

    @Test func decodesEntitiesAndBreaks() {
        let cues = TranscriptLogic.parseTTML(ttml)
        // <br/> becomes a space; &#39; decodes to an apostrophe.
        #expect(cues[1].text == "We're no strangers to love")
    }

    @Test func emptyForNonTTML() {
        #expect(TranscriptLogic.parseTTML("not xml at all").isEmpty)
    }

    // MARK: - bestTrack

    private func sub(_ name: String, _ code: String, auto: Bool) -> Subtitle {
        Subtitle(url: "https://x/\(name)", name: name, code: code, autoGenerated: auto)
    }

    @Test func prefersHumanOverAutoGenerated() {
        let tracks = [sub("auto", "en", auto: true), sub("human", "en", auto: false)]
        #expect(TranscriptLogic.bestTrack(from: tracks, preferredLanguage: "en")?.name == "human")
    }

    @Test func prefersPreferredLanguageAmongHuman() {
        let tracks = [sub("en", "en", auto: false), sub("es", "es", auto: false)]
        #expect(TranscriptLogic.bestTrack(from: tracks, preferredLanguage: "es")?.code == "es")
    }

    @Test func fallsBackToAutoWhenNoHuman() {
        let tracks = [sub("auto", "fr", auto: true)]
        #expect(TranscriptLogic.bestTrack(from: tracks, preferredLanguage: "en")?.name == "auto")
    }

    @Test func nilWhenNoTracks() {
        #expect(TranscriptLogic.bestTrack(from: nil, preferredLanguage: "en") == nil)
        #expect(TranscriptLogic.bestTrack(from: [], preferredLanguage: "en") == nil)
    }

    // MARK: - plainText

    @Test func joinsCueText() {
        let cues = [TranscriptCue(start: 0, text: "one"), TranscriptCue(start: 1, text: "two")]
        #expect(TranscriptLogic.plainText(from: cues) == "one two")
    }
}
