import Foundation

/// Full metadata for a single video: streams, chapters, related videos.
struct StreamResponse: Codable, Equatable {
    let title: String
    let description: String?
    let uploader: String
    let uploaderUrl: String?
    let duration: Int
    let hls: String?
    let audioStreams: [AudioStream]
    let videoStreams: [VideoStream]
    let thumbnailUrl: String
    let uploadDate: String?
    let chapters: [Chapter]?
    let relatedStreams: [RelatedStream]?
    /// Caption tracks (TTML) offered for the video. Decodes to nil when absent;
    /// the inline default keeps existing memberwise initializers source-stable.
    var subtitles: [Subtitle]? = nil
}

/// A caption/subtitle track as returned by Piped. `url` points at a TTML
/// document; `autoGenerated` marks machine transcription (lower quality).
struct Subtitle: Codable, Equatable {
    let url: String
    let name: String?
    let code: String?
    let autoGenerated: Bool?
}

/// A YouTube chapter timeline marker, as returned by Piped.
struct Chapter: Codable, Equatable, Identifiable {
    let title: String
    let start: Int      // seconds from the start of the video
    let image: String?

    var id: Int { start }
}

struct AudioStream: Codable, Equatable {
    let url: String
    let bitrate: Int
    let mimeType: String
}

struct VideoStream: Codable, Equatable {
    let url: String
    let quality: String
    let mimeType: String
    let videoOnly: Bool?
}
