import Foundation

/// One line of a transcript: the text and the video time it starts at.
struct TranscriptCue: Equatable, Identifiable {
    let start: Double   // seconds from the start of the video
    let text: String

    var id: Double { start }
}

/// Pure, WebKit-free helpers for turning Piped's TTML caption tracks into a
/// tappable transcript. Kept out of the view/store so parsing is unit-testable.
enum TranscriptLogic {
    /// Parse a TTML document into cues, in document order. Extracts each
    /// `<p begin="hh:mm:ss.mmm" …>text</p>`, converts `<br/>` to spaces,
    /// decodes entities (reusing `HTMLText`), and drops cues with empty text.
    static func parseTTML(_ xml: String) -> [TranscriptCue] {
        guard let regex = try? NSRegularExpression(
            pattern: "<p\\b[^>]*\\bbegin=\"([^\"]+)\"[^>]*>(.*?)</p>",
            options: [.dotMatchesLineSeparators, .caseInsensitive]) else { return [] }
        let range = NSRange(xml.startIndex..., in: xml)
        var cues: [TranscriptCue] = []
        for match in regex.matches(in: xml, range: range) {
            guard let beginRange = Range(match.range(at: 1), in: xml),
                  let bodyRange = Range(match.range(at: 2), in: xml),
                  let start = seconds(fromClock: String(xml[beginRange])) else { continue }
            let text = cleanText(String(xml[bodyRange]))
            guard !text.isEmpty else { continue }
            cues.append(TranscriptCue(start: start, text: text))
        }
        return cues
    }

    /// Parse a TTML clock value (`hh:mm:ss.mmm`, `mm:ss`, or seconds) to seconds.
    static func seconds(fromClock clock: String) -> Double? {
        let parts = clock.split(separator: ":").map(String.init)
        guard !parts.isEmpty, parts.count <= 3 else { return nil }
        var total = 0.0
        for part in parts {
            guard let value = Double(part) else { return nil }
            total = total * 60 + value
        }
        return total
    }

    /// Strip inline tags, decode entities, and collapse whitespace to one line.
    private static func cleanText(_ raw: String) -> String {
        let noTags = raw.replacingOccurrences(
            of: "<[^>]+>", with: " ", options: .regularExpression)
        let decoded = HTMLText.decodeEntities(noTags)
        return decoded.split(whereSeparator: \.isWhitespace).joined(separator: " ")
    }

    /// Choose the best caption track: prefer a human (non-auto-generated) one,
    /// then one matching the device language, else the first. Nil if none.
    static func bestTrack(from subtitles: [Subtitle]?, preferredLanguage: String) -> Subtitle? {
        guard let subtitles, !subtitles.isEmpty else { return nil }
        let human = subtitles.filter { $0.autoGenerated != true }
        let pool = human.isEmpty ? subtitles : human
        return pool.first { $0.code == preferredLanguage } ?? pool.first
    }

    /// The transcript as one block of plain text, for the summarizer.
    static func plainText(from cues: [TranscriptCue]) -> String {
        cues.map(\.text).joined(separator: " ")
    }
}
